
variables {
  namespace              = "dltmx"
  compact_name           = "test"
  region                 = "us-east-1"
  source_ami             = "ami-0cff7528ff583bf9a"
  ansible_playbooks_repo = "git@github.com:SlatamCloud/ansible-playbooks.git"
  playbooks_path         = "/tmp/playbooks"
  tomcat_version         = "9.0.65"
  env                    = "dev"
  war_download_url       = "https://raw.githubusercontent.com/aeimer/java-example-helloworld-war/master/dist/helloworld.war"
}

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "${var.namespace}-${var.compact_name}-${var.env}-tomcat-${var.tomcat_version}"
  instance_type = "t2.micro"
  region        = "${var.region}"
  source_ami    = "${var.source_ami}"
  ssh_username  = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp"
    source      = "./files/ssh"
  }

  provisioner "shell" {
    script = "prerequisites.sh"
  }

  provisioner "shell" {
    inline = ["mkdir ${var.playbooks_path} && git clone ${var.ansible_playbooks_repo} ${var.playbooks_path}"]
  }

  provisioner "file" {
    destination = "${var.playbooks_path}/files/server.xml"
    source      = "./files/server.xml"
  }

  provisioner "file" {
    destination = "${var.playbooks_path}/vars/variables.json"
    source      = "./vars/commons.json"
  }

  provisioner "shell" {
    inline = ["cd ${var.playbooks_path} && ansible-playbook tomcat_war_deployment.yml --extra-vars @./vars/variables.json --extra-vars 'war_download_url=${var.war_download_url}'"]
  }
  /*
  provisioner "shell" {
    inline = ["cd ${var.playbooks_path} && ansible-playbook hardening.yml --extra-vars @./vars/variables.json"]
  }
*/
}
